services:
  emporio-api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    image: emporio-api
    container_name: emporio-api
    restart: unless-stopped
    ports:
      - '5012:5012'
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    #   API_PORT: ${API_PORT}
    #   API_HOST: ${API_HOST}
    networks:
      - atlas
    volumes:
      - /var/log/emporio:/var/log/emporio
networks:
  atlas:
    name: stickerapp_atlas
    external: true