services:
  emporio-api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    image: emporio-api
    container_name: emporio-api
    ports:
      - '5012:5012'
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
    networks:
      - atlas
networks:
  atlas:
    name: stickerapp_atlas
    external: true