name: ProductionLineConstraint
rules:
  - keys:
      - DIGITAL
    conditions:
      relationMode: AND
      conditions:
        - attribute: material
          operator: IN
          value: "{DigitalMaterials}"
        - attribute: laminate
          operator: IN
          value: "{DigitalLaminates}"
        - attribute: feature
          operator: NOT_IN
          value:
            - "{ProductFeatures.BACKPAPER_PRINT}"

  - keys:
      - LASER
    conditions:
      relationMode: AND
      baseComplexityScore: 2
      conditions:
        - attribute: material
          operator: IN
          value: "{LaserMaterials}"
        - attribute: laminate
          operator: IN
          value: "{LaserLaminates}"
        - attribute: width_mm
          operator: <=
          value: "{MaxSizes.ONE_SIDE_LASER}"
        - attribute: height_mm
          operator: <=
          value: "{MaxSizes.ONE_SIDE_LASER}"
        - relationMode: OR
          baseComplexityScore: 1
          conditions:
            - attribute: width_mm
              operator: <=
              value: "{MaxSizes.LASER}"
            - attribute: height_mm
              operator: <=
              value: "{MaxSizes.LASER}"

  - keys:
      - SPECIAL
    conditions:
      relationMode: AND
      conditions:
        - attribute: material
          operator: ===
          value: "{ProductionLines.SPECIAL}"
