name: StickerSquareMeterMinimumUnitValues
defaultValue: 0.1407
rules:
  - keys: 0.5
    conditions:
      baseComplexityScore: 120
      relationMode: AND
      conditions:
        - attribute: item.productName
          operator: ===
          value: "{ProductNames.PRODUCT_LABELS_ON_ROLL}"
  - keys: 0.1090
    conditions:
      baseComplexityScore: 1
      conditions:
        - attribute: item.attributes.material
          operator: IN
          value: [holographic, glitter, mirror, prismatic, pixie_dust]
  - keys: 0.1360
    conditions:
      baseComplexityScore: 1
      conditions:
        - attribute: item.attributes.material
          operator: IN
          value: [white_hi_tack]
  - keys: 0.1635
    conditions:
      baseComplexityScore: 1
      conditions:
        - attribute: item.attributes.material
          operator: IN
          value: [gitd]
  - keys: 0.1440
    conditions:
      baseComplexityScore: 1
      conditions:
        - attribute: item.attributes.material
          operator: IN
          value: [clear]
        - attribute: item.productName
          operator: "!=="
          value: "{ProductNames.PRODUCT_LABELS_ON_SHEET}"
  - keys: 0.35
    conditions:
      baseComplexityScore: 1
      conditions:
        - attribute: item.attributes.material
          operator: IN
          value: [white_wall]
  - keys: 0.058
    conditions:
      conditions:
        - attribute: item.attributes.laminate
          operator: ===
          value: epoxy
  - keys: 0.06
    conditions:
      baseComplexityScore: 10
      conditions:
        - attribute: item.productName
          operator: ===
          value: ProductNames.PRODUCT_SHEET_LEGACY
