name: ProductionLineFilter
mode: highest_score_wins
rules:
  - keys:
      - laser
    conditions:
      relationMode: and
      baseComplexityScore: 120
      conditions:
        - attribute: item.productName
          operator: in
          value:
            - sheet
            - sheet_kiss_cut
            - window
            - labels_on_roll
            - labels_on_sheet

  - keys:
      - laser
    conditions:
      relationMode: and
      conditions:
        - attribute: item.attributes.material
          operator: in
          value:
            - white
            - white_removable
            - clear
        - attribute: item.productName
          operator: "!=="
          value: library_design
        - attribute: item.attributes.width_mm
          operator: <=
          value: 800
        - attribute: item.attributes.height_mm
          operator: <=
          value: 800
        - relationMode: or
          conditions:
            - attribute: item.attributes.width_mm
              operator: <=
              value: 275
            - attribute: item.attributes.height_mm
              operator: <=
              value: 275

  - keys:
      - digital
    conditions:
      relationMode: or
      conditions:
        - attribute: item.productName
          operator: in
          value:
            - transfer_decal
        - relationMode: and
          conditions:
            - attribute: item.attributes.width_mm
              operator: ">"
              value: 275
            - attribute: item.attributes.height_mm
              operator: ">"
              value: 275