<?php

	namespace StickerApp\Babylon\Commerce\Core\Product\Condition;

	use ErrorException;
	use StickerApp\Babylon\Commerce\Core\Product\Item\ProductItem;
	use StickerApp\Babylon\Helper\Condition\ConditionBuilder;
    use StickerApp\Babylon\Helper\Condition\Exception\ConditionTestDataKeyNotFoundException;

	class ProductConditionBuilder extends ConditionBuilder
	{
        /**
		 * @throws Exception\ConditionTestFailedException
		 * @throws Exception\ConditionTestDataKeyNotFoundException
		 */
		public function testOnItem( ProductItem $item ): bool
		{
			return parent::test( $item->toTestableOneDimensionalArray() );
		}

		public function test( array $data ): bool
		{
			throw new ErrorException( "Don't use test(). Use testOnItem()." );

			return parent::test( $data ); // TODO: Change the autogenerated stub
		}
	}
