name: Emporio api build and push docker image

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - docker/api.Dockerfile
  workflow_dispatch:

jobs:
  emporio-api-build-push-docker-image:
    name: Emporio api build and push docker image
    uses: stickerapp-org/stickerapp/.github/workflows/build-push-docker-image.yml@main
    secrets: inherit
    with:
      service: emporio-api
      docker-file: docker/api.Dockerfile
