name: Build and push docker image

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      docker-file:
        required: true
        type: string

jobs:
  build-push-docker-image:
    name: Build and push ${{ inputs.service }} docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docker tag
        run: |
          docker_tag=$(git rev-parse --short=10 "${{ github.sha }}")
          echo "docker_tag=$docker_tag" >> $GITHUB_ENV
          echo "repository=stickerapp/${{ inputs.service }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.docker-file }}
          push: true
          tags: ${{ env.repository }}:${{ env.docker_tag }},${{ env.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
           NODE_AUTH_TOKEN=${{secrets.NODE_AUTH_TOKEN}}
      - name: Notify Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> on <{commit_url}|${{ env.docker_tag }}>"
          message_format: |
            *Tag:* ${{ env.docker_tag }}
            *Repository:* ${{ env.repository }}:${{ env.docker_tag }}
          footer: "<{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}